development:
  adapter: postgresql
  encoding: unicode
  database: rails_ui_dev
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: rails_ui_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: <%= Rails.application.secrets.pg_db_name %>
  pool: 25
  username: <%= Rails.application.secrets.pg_user %>
  password: <%= Rails.application.secrets.pg_pass %>
